INFO:app:Database connection successful
Traceback (most recent call last):
  File "/home/configman/repos/opsmanager/app/app.py", line 784, in <module>
    socketio.run(app, host='0.0.0.0', debug=True, port=5000)
  File "/home/configman/miniconda3/envs/opsmanager/lib/python3.10/site-packages/flask_socketio/__init__.py", line 640, in run
    raise RuntimeError('The Werkzeug web server is not '
RuntimeError: The Werkzeug web server is not designed to run in production. Pass allow_unsafe_werkzeug=True to the run() method to disable this error.
